=begin
#testapi

#A Simple Test API

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.1

=end

module SwaggerClient
  VERSION = '1.0.0'
end
