// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateAsyncActionHandlerFunc turns a function with the right signature into a create async action handler
type CreateAsyncActionHandlerFunc func(CreateAsyncActionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateAsyncActionHandlerFunc) Handle(params CreateAsyncActionParams) middleware.Responder {
	return fn(params)
}

// CreateAsyncActionHandler interface for that can handle valid create async action params
type CreateAsyncActionHandler interface {
	Handle(CreateAsyncActionParams) middleware.Responder
}

// NewCreateAsyncAction creates a new http.Handler for the create async action operation
func NewCreateAsyncAction(ctx *middleware.Context, handler CreateAsyncActionHandler) *CreateAsyncAction {
	return &CreateAsyncAction{Context: ctx, Handler: handler}
}

/*CreateAsyncAction swagger:route PUT /actions createAsyncAction

Creates a asynchronous action.

*/
type CreateAsyncAction struct {
	Context *middleware.Context
	Handler CreateAsyncActionHandler
}

func (o *CreateAsyncAction) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateAsyncActionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
