// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi testapi
A Simple Test API


    Schemes:
      https
    Host: localhost
    BasePath: /
    Version: v1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
