// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A Simple Test API",
    "title": "testapi",
    "version": "v1"
  },
  "basePath": "/",
  "paths": {
    "/": {
      "get": {
        "summary": "Get client profile",
        "responses": {
          "200": {
            "description": "The instance information",
            "schema": {
              "$ref": "#/definitions/Profile"
            }
          },
          "default": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/actions": {
      "put": {
        "summary": "Creates a asynchronous action.",
        "operationId": "createAsyncAction",
        "parameters": [
          {
            "name": "info",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ActionInfo"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "The update was successful"
          },
          "400": {
            "description": "The action cannot be executed due to bad input",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ActionInfo": {
      "description": "Variant wrapper containing the real action.",
      "type": "object",
      "required": [
        "action_type"
      ],
      "properties": {
        "action_type": {
          "description": "Enumeration indicating what type of action is contained in the payload",
          "type": "string",
          "enum": [
            "RunCommand",
            "RunAPI"
          ]
        },
        "payload": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "properties": {
        "message": {
          "description": "A description of the error condition",
          "type": "string"
        }
      }
    },
    "Profile": {
      "type": "object",
      "properties": {
        "message": {
          "description": "A description of the application",
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A Simple Test API",
    "title": "testapi",
    "version": "v1"
  },
  "basePath": "/",
  "paths": {
    "/": {
      "get": {
        "summary": "Get client profile",
        "responses": {
          "200": {
            "description": "The instance information",
            "schema": {
              "$ref": "#/definitions/Profile"
            }
          },
          "default": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/actions": {
      "put": {
        "summary": "Creates a asynchronous action.",
        "operationId": "createAsyncAction",
        "parameters": [
          {
            "name": "info",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ActionInfo"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "The update was successful"
          },
          "400": {
            "description": "The action cannot be executed due to bad input",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ActionInfo": {
      "description": "Variant wrapper containing the real action.",
      "type": "object",
      "required": [
        "action_type"
      ],
      "properties": {
        "action_type": {
          "description": "Enumeration indicating what type of action is contained in the payload",
          "type": "string",
          "enum": [
            "RunCommand",
            "RunAPI"
          ]
        },
        "payload": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "properties": {
        "message": {
          "description": "A description of the error condition",
          "type": "string"
        }
      }
    },
    "Profile": {
      "type": "object",
      "properties": {
        "message": {
          "description": "A description of the application",
          "type": "string"
        }
      }
    }
  }
}`))
}
