// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A Simple Test API",
    "title": "testapi",
    "version": "v1"
  },
  "basePath": "/",
  "paths": {
    "/": {
      "get": {
        "summary": "Get client profile",
        "responses": {
          "200": {
            "description": "Success response"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A Simple Test API",
    "title": "testapi",
    "version": "v1"
  },
  "basePath": "/",
  "paths": {
    "/": {
      "get": {
        "summary": "Get client profile",
        "responses": {
          "200": {
            "description": "Success response"
          }
        }
      }
    }
  }
}`))
}
