# coding: utf-8

# flake8: noqa
"""
    testapi

    A Simple Test API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
