// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mcastelino/testapi/models"
)

// NewCreateAsyncActionParams creates a new CreateAsyncActionParams object
// with the default values initialized.
func NewCreateAsyncActionParams() *CreateAsyncActionParams {
	var ()
	return &CreateAsyncActionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateAsyncActionParamsWithTimeout creates a new CreateAsyncActionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateAsyncActionParamsWithTimeout(timeout time.Duration) *CreateAsyncActionParams {
	var ()
	return &CreateAsyncActionParams{

		timeout: timeout,
	}
}

// NewCreateAsyncActionParamsWithContext creates a new CreateAsyncActionParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateAsyncActionParamsWithContext(ctx context.Context) *CreateAsyncActionParams {
	var ()
	return &CreateAsyncActionParams{

		Context: ctx,
	}
}

// NewCreateAsyncActionParamsWithHTTPClient creates a new CreateAsyncActionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateAsyncActionParamsWithHTTPClient(client *http.Client) *CreateAsyncActionParams {
	var ()
	return &CreateAsyncActionParams{
		HTTPClient: client,
	}
}

/*CreateAsyncActionParams contains all the parameters to send to the API endpoint
for the create async action operation typically these are written to a http.Request
*/
type CreateAsyncActionParams struct {

	/*Info*/
	Info *models.ActionInfo

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create async action params
func (o *CreateAsyncActionParams) WithTimeout(timeout time.Duration) *CreateAsyncActionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create async action params
func (o *CreateAsyncActionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create async action params
func (o *CreateAsyncActionParams) WithContext(ctx context.Context) *CreateAsyncActionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create async action params
func (o *CreateAsyncActionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create async action params
func (o *CreateAsyncActionParams) WithHTTPClient(client *http.Client) *CreateAsyncActionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create async action params
func (o *CreateAsyncActionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInfo adds the info to the create async action params
func (o *CreateAsyncActionParams) WithInfo(info *models.ActionInfo) *CreateAsyncActionParams {
	o.SetInfo(info)
	return o
}

// SetInfo adds the info to the create async action params
func (o *CreateAsyncActionParams) SetInfo(info *models.ActionInfo) {
	o.Info = info
}

// WriteToRequest writes these params to a swagger request
func (o *CreateAsyncActionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Info != nil {
		if err := r.SetBodyParam(o.Info); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
